services:
  fastapi-app:
    build:
     context: .
    image: fastapi_app
    restart: unless-stopped
    working_dir: /code
    ports:
      - '8080:8000'
    stop_signal: SIGKILL
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - monitor-net

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    stop_signal: SIGKILL
    networks:
      - monitor-net

  celery_worker:
    build:
      context: .
    image: fastapi_celery
    working_dir: /code/app
    restart: unless-stopped
    command: celery -A celery_tasks.run_celery worker -E --loglevel INFO
    depends_on:
      - redis
    links:
      - redis
    networks:
      - monitor-net

  prometheus:
    user: root
    build:
      context: prometheus
    image: prometheus
    ports:
      - '9090:9090'
    stop_signal: SIGKILL
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - fastapi-app
    networks:
      - monitor-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/locust:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
    stop_signal: SIGKILL
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitor-net


  locust_master:
    image: locustio/locust
    ports:
      - "8089:8089"
    environment:
      - LOCUSTFILE
    volumes:
      - ./locust/:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE}.py --master -H http://fastapi-app:8000
    networks:
      - monitor-net

  locust_worker:
    image: locustio/locust
    volumes:
      - ./locust/:/mnt/locust
    environment:
      - LOCUSTFILE
    command: -f /mnt/locust/${LOCUSTFILE}.py --worker --master-host locust_master
    networks:
      - monitor-net

  locust-metrics-exporter:
    image: containersol/locust_exporter
    ports:
      - "9646:9646"
    environment:
      - LOCUST_EXPORTER_URI=http://locust_master:8089
    depends_on:
      - locust_master
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}