#version: '3'
services:
  fastapi-app:
    build:
     context: .
    image: fastapi_app
    ports:
      - '8080:8000'
    stop_signal: SIGKILL
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - monitor-net

  redis:
    image: redis:latest
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./grafana/loki_config.yaml:/etc/loki/loki.yaml
    networks:
      - monitor-net

  celery_worker:
    build:
      context: .
    image: fastapi_celery
    restart: always
    command: celery -A celery_tasks.run_celery worker -E --loglevel INFO
    depends_on:
      - redis
    links:
      - redis:redis

  prometheus:
    build:
      context: prometheus
    image: prometheus
    ports:
      - '9090:9090'
    stop_signal: SIGKILL
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - fastapi-app
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/var/lib/grafana/dashboards/default.yaml
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
    stop_signal: SIGKILL
    depends_on:
      - prometheus
    networks:
      - monitor-net

  alloy:
    volumes:
      - './grafana/config.alloy:/etc/alloy/config.alloy'
    ports:
      - '12345:12345'
    image: 'grafana/alloy:latest'
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}