[tool.poetry]
name = "weatherfastapi"
version = "0.1.0"
description = ""
authors = ["vitaly <vitaly.rybkin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.4"
uvicorn = {extras = ["starndart"], version = "^0.32.0"}
sqlalchemy = {extras = ["asincio"], version = "^2.0.36"}
python-dotenv = "^1.0.1"
pydantic-settings = "^2.6.0"
pydantic = {extras = ["email"], version = "^2.9.2"}
asyncpg = "^0.30.0"
email-validator = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
