global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'app'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["localhost:9090"]

  - job_name: 'fastapi-app'

#    dns_sd_configs:
#      - names: ['app']
#        port: 8080
#        type: A
#        refresh_interval: 5s
    static_configs:
      - targets: ["fastapi-app:8000"]

  - job_name: locust_scrapper
    scrape_interval: 5s
    static_configs:
      - targets: ["locust-metrics-exporter:9646"]