apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    typeName: Prometheus
    editable: true
    is_default: true
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus

